AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi

  CreateTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: create.handler
      Events:
        Create:
          Type: HttpApi
          Properties:
            Path: /api/todos
            Method: post
            ApiId: !Ref HttpApi
      Environment:
        Variables:
          TODO_TABLE: todo-items
      Policies:
        - DynamoDBCrudPolicy:
            TableName: todo-items

  ListTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: list.handler
      Events:
        List:
          Type: HttpApi
          Properties:
            Path: /api/todos
            Method: get
            ApiId: !Ref HttpApi
      Environment:
        Variables:
          TODO_TABLE: todo-items
      Policies:
        - DynamoDBReadPolicy:
            TableName: todo-items

  UpdateTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: update.handler
      Events:
        Update:
          Type: HttpApi
          Properties:
            Path: /api/todos/{id}
            Method: put
            ApiId: !Ref HttpApi
      Environment:
        Variables:
          TODO_TABLE: todo-items
      Policies:
        - DynamoDBCrudPolicy:
            TableName: todo-items

  DeleteTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: delete.handler
      Events:
        Delete:
          Type: HttpApi
          Properties:
            Path: /api/todos/{id}
            Method: delete
            ApiId: !Ref HttpApi
      Environment:
        Variables:
          TODO_TABLE: todo-items
      Policies:
        - DynamoDBCrudPolicy:
            TableName: todo-items

  TodoTable:
    Type: AWS::Serverless::SimpleTable # SAM shorthand
    Properties:
      TableName: todo-items
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  ApiOrigin:
    Value: !Sub "${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: TodoApiOrigin
